/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  "demo_function_hide-child_one": () => import("@/views/demo/function/hide-child/one/index.vue"),
  "demo_function_hide-child_three": () => import("@/views/demo/function/hide-child/three/index.vue"),
  "demo_function_hide-child_two": () => import("@/views/demo/function/hide-child/two/index.vue"),
  "demo_function_multi-tab": () => import("@/views/demo/function/multi-tab/index.vue"),
  demo_function_request: () => import("@/views/demo/function/request/index.vue"),
  "demo_function_super-page": () => import("@/views/demo/function/super-page/index.vue"),
  demo_function_tab: () => import("@/views/demo/function/tab/index.vue"),
  "demo_function_toggle-auth": () => import("@/views/demo/function/toggle-auth/index.vue"),
  "demo_multi-menu_first_child": () => import("@/views/demo/multi-menu/first_child/index.vue"),
  "demo_multi-menu_second_child_home": () => import("@/views/demo/multi-menu/second_child_home/index.vue"),
  demo_plugin_barcode: () => import("@/views/demo/plugin/barcode/index.vue"),
  demo_plugin_charts_echarts: () => import("@/views/demo/plugin/charts/echarts/index.vue"),
  demo_plugin_copy: () => import("@/views/demo/plugin/copy/index.vue"),
  demo_plugin_editor_markdown: () => import("@/views/demo/plugin/editor/markdown/index.vue"),
  demo_plugin_editor_quill: () => import("@/views/demo/plugin/editor/quill/index.vue"),
  demo_plugin_excel: () => import("@/views/demo/plugin/excel/index.vue"),
  demo_plugin_gantt: () => import("@/views/demo/plugin/gantt/index.vue"),
  demo_plugin_icon: () => import("@/views/demo/plugin/icon/index.vue"),
  demo_plugin_map: () => import("@/views/demo/plugin/map/index.vue"),
  demo_plugin_pdf: () => import("@/views/demo/plugin/pdf/index.vue"),
  demo_plugin_pinyin: () => import("@/views/demo/plugin/pinyin/index.vue"),
  demo_plugin_print: () => import("@/views/demo/plugin/print/index.vue"),
  demo_plugin_swiper: () => import("@/views/demo/plugin/swiper/index.vue"),
  demo_plugin_typeit: () => import("@/views/demo/plugin/typeit/index.vue"),
  demo_plugin_video: () => import("@/views/demo/plugin/video/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_api: () => import("@/views/manage/api/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_platform: () => import("@/views/manage/platform/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  manage_tenant: () => import("@/views/manage/tenant/index.vue"),
  "manage_user-center": () => import("@/views/manage/user-center/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
};
