/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 10
    }
  },
  {
    name: 'demo',
    path: '/demo',
    component: 'layout.base',
    meta: {
      title: 'demo',
      i18nKey: 'route.demo'
    },
    children: [
      {
        name: 'demo_function',
        path: '/demo/function',
        meta: {
          title: 'demo_function',
          i18nKey: 'route.demo_function'
        },
        children: [
          {
            name: 'demo_function_hide-child',
            path: '/demo/function/hide-child',
            meta: {
              title: 'demo_function_hide-child',
              i18nKey: 'route.demo_function_hide-child'
            },
            children: [
              {
                name: 'demo_function_hide-child_one',
                path: '/demo/function/hide-child/one',
                component: 'view.demo_function_hide-child_one',
                meta: {
                  title: 'demo_function_hide-child_one',
                  i18nKey: 'route.demo_function_hide-child_one'
                }
              },
              {
                name: 'demo_function_hide-child_three',
                path: '/demo/function/hide-child/three',
                component: 'view.demo_function_hide-child_three',
                meta: {
                  title: 'demo_function_hide-child_three',
                  i18nKey: 'route.demo_function_hide-child_three'
                }
              },
              {
                name: 'demo_function_hide-child_two',
                path: '/demo/function/hide-child/two',
                component: 'view.demo_function_hide-child_two',
                meta: {
                  title: 'demo_function_hide-child_two',
                  i18nKey: 'route.demo_function_hide-child_two'
                }
              }
            ]
          },
          {
            name: 'demo_function_multi-tab',
            path: '/demo/function/multi-tab',
            component: 'view.demo_function_multi-tab',
            meta: {
              title: 'demo_function_multi-tab',
              i18nKey: 'route.demo_function_multi-tab'
            }
          },
          {
            name: 'demo_function_request',
            path: '/demo/function/request',
            component: 'view.demo_function_request',
            meta: {
              title: 'demo_function_request',
              i18nKey: 'route.demo_function_request'
            }
          },
          {
            name: 'demo_function_super-page',
            path: '/demo/function/super-page',
            component: 'view.demo_function_super-page',
            meta: {
              title: 'demo_function_super-page',
              i18nKey: 'route.demo_function_super-page'
            }
          },
          {
            name: 'demo_function_tab',
            path: '/demo/function/tab',
            component: 'view.demo_function_tab',
            meta: {
              title: 'demo_function_tab',
              i18nKey: 'route.demo_function_tab'
            }
          },
          {
            name: 'demo_function_toggle-auth',
            path: '/demo/function/toggle-auth',
            component: 'view.demo_function_toggle-auth',
            meta: {
              title: 'demo_function_toggle-auth',
              i18nKey: 'route.demo_function_toggle-auth'
            }
          }
        ]
      },
      {
        name: 'demo_multi-menu',
        path: '/demo/multi-menu',
        meta: {
          title: 'demo_multi-menu',
          i18nKey: 'route.demo_multi-menu'
        },
        children: [
          {
            name: 'demo_multi-menu_first',
            path: '/demo/multi-menu/first',
            meta: {
              title: 'demo_multi-menu_first',
              i18nKey: 'route.demo_multi-menu_first'
            },
            children: [
              {
                name: 'demo_multi-menu_first_child',
                path: '/demo/multi-menu/first/child',
                component: 'view.demo_multi-menu_first_child',
                meta: {
                  title: 'demo_multi-menu_first_child',
                  i18nKey: 'route.demo_multi-menu_first_child'
                }
              }
            ]
          },
          {
            name: 'demo_multi-menu_second',
            path: '/demo/multi-menu/second',
            meta: {
              title: 'demo_multi-menu_second',
              i18nKey: 'route.demo_multi-menu_second'
            },
            children: [
              {
                name: 'demo_multi-menu_second_child',
                path: '/demo/multi-menu/second/child',
                meta: {
                  title: 'demo_multi-menu_second_child',
                  i18nKey: 'route.demo_multi-menu_second_child'
                },
                children: [
                  {
                    name: 'demo_multi-menu_second_child_home',
                    path: '/demo/multi-menu/second/child/home',
                    component: 'view.demo_multi-menu_second_child_home',
                    meta: {
                      title: 'demo_multi-menu_second_child_home',
                      i18nKey: 'route.demo_multi-menu_second_child_home'
                    }
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        name: 'demo_plugin',
        path: '/demo/plugin',
        meta: {
          title: 'demo_plugin',
          i18nKey: 'route.demo_plugin'
        },
        children: [
          {
            name: 'demo_plugin_barcode',
            path: '/demo/plugin/barcode',
            component: 'view.demo_plugin_barcode',
            meta: {
              title: 'demo_plugin_barcode',
              i18nKey: 'route.demo_plugin_barcode'
            }
          },
          {
            name: 'demo_plugin_charts',
            path: '/demo/plugin/charts',
            meta: {
              title: 'demo_plugin_charts',
              i18nKey: 'route.demo_plugin_charts'
            },
            children: [
              {
                name: 'demo_plugin_charts_echarts',
                path: '/demo/plugin/charts/echarts',
                component: 'view.demo_plugin_charts_echarts',
                meta: {
                  title: 'demo_plugin_charts_echarts',
                  i18nKey: 'route.demo_plugin_charts_echarts'
                }
              }
            ]
          },
          {
            name: 'demo_plugin_copy',
            path: '/demo/plugin/copy',
            component: 'view.demo_plugin_copy',
            meta: {
              title: 'demo_plugin_copy',
              i18nKey: 'route.demo_plugin_copy'
            }
          },
          {
            name: 'demo_plugin_editor',
            path: '/demo/plugin/editor',
            meta: {
              title: 'demo_plugin_editor',
              i18nKey: 'route.demo_plugin_editor'
            },
            children: [
              {
                name: 'demo_plugin_editor_markdown',
                path: '/demo/plugin/editor/markdown',
                component: 'view.demo_plugin_editor_markdown',
                meta: {
                  title: 'demo_plugin_editor_markdown',
                  i18nKey: 'route.demo_plugin_editor_markdown'
                }
              },
              {
                name: 'demo_plugin_editor_quill',
                path: '/demo/plugin/editor/quill',
                component: 'view.demo_plugin_editor_quill',
                meta: {
                  title: 'demo_plugin_editor_quill',
                  i18nKey: 'route.demo_plugin_editor_quill'
                }
              }
            ]
          },
          {
            name: 'demo_plugin_excel',
            path: '/demo/plugin/excel',
            component: 'view.demo_plugin_excel',
            meta: {
              title: 'demo_plugin_excel',
              i18nKey: 'route.demo_plugin_excel'
            }
          },
          {
            name: 'demo_plugin_gantt',
            path: '/demo/plugin/gantt',
            component: 'view.demo_plugin_gantt',
            meta: {
              title: 'demo_plugin_gantt',
              i18nKey: 'route.demo_plugin_gantt'
            }
          },
          {
            name: 'demo_plugin_icon',
            path: '/demo/plugin/icon',
            component: 'view.demo_plugin_icon',
            meta: {
              title: 'demo_plugin_icon',
              i18nKey: 'route.demo_plugin_icon'
            }
          },
          {
            name: 'demo_plugin_map',
            path: '/demo/plugin/map',
            component: 'view.demo_plugin_map',
            meta: {
              title: 'demo_plugin_map',
              i18nKey: 'route.demo_plugin_map'
            }
          },
          {
            name: 'demo_plugin_pdf',
            path: '/demo/plugin/pdf',
            component: 'view.demo_plugin_pdf',
            meta: {
              title: 'demo_plugin_pdf',
              i18nKey: 'route.demo_plugin_pdf'
            }
          },
          {
            name: 'demo_plugin_pinyin',
            path: '/demo/plugin/pinyin',
            component: 'view.demo_plugin_pinyin',
            meta: {
              title: 'demo_plugin_pinyin',
              i18nKey: 'route.demo_plugin_pinyin'
            }
          },
          {
            name: 'demo_plugin_print',
            path: '/demo/plugin/print',
            component: 'view.demo_plugin_print',
            meta: {
              title: 'demo_plugin_print',
              i18nKey: 'route.demo_plugin_print'
            }
          },
          {
            name: 'demo_plugin_swiper',
            path: '/demo/plugin/swiper',
            component: 'view.demo_plugin_swiper',
            meta: {
              title: 'demo_plugin_swiper',
              i18nKey: 'route.demo_plugin_swiper'
            }
          },
          {
            name: 'demo_plugin_typeit',
            path: '/demo/plugin/typeit',
            component: 'view.demo_plugin_typeit',
            meta: {
              title: 'demo_plugin_typeit',
              i18nKey: 'route.demo_plugin_typeit'
            }
          },
          {
            name: 'demo_plugin_video',
            path: '/demo/plugin/video',
            component: 'view.demo_plugin_video',
            meta: {
              title: 'demo_plugin_video',
              i18nKey: 'route.demo_plugin_video'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 0,
      module: 'ALL'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9,
      module: 'System'
    },
    children: [
      {
        name: 'manage_api',
        path: '/manage/api',
        component: 'view.manage_api',
        meta: {
          title: 'manage_api',
          i18nKey: 'route.manage_api'
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          keepAlive: true
        }
      },
      {
        name: 'manage_platform',
        path: '/manage/platform',
        component: 'view.manage_platform',
        meta: {
          title: 'manage_platform',
          i18nKey: 'route.manage_platform'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2
        }
      },
      {
        name: 'manage_tenant',
        path: '/manage/tenant',
        component: 'view.manage_tenant',
        meta: {
          title: 'manage_tenant',
          i18nKey: 'route.manage_tenant'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1
        }
      },
      {
        name: 'manage_user-center',
        path: '/manage/user-center',
        component: 'view.manage_user-center',
        children: [],
        meta: {
          title: 'manage_user-center',
          i18nKey: 'route.manage_user-center',
          hideInMenu: true,
          activeMenu: 'manage_user'
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          activeMenu: 'manage_user'
        }
      }
    ]
  }
];
