/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteRecordRaw, RouteComponent } from 'vue-router';
import type { ElegantConstRoute } from '@elegant-router/vue';
import type { RouteMap, RouteKey, RoutePath } from '@elegant-router/types';

/**
 * transform elegant const routes to vue routes
 * @param routes elegant const routes
 * @param layouts layout components
 * @param views view components
 */
export function transformElegantRoutesToVueRoutes(
  routes: ElegantConstRoute[],
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  return routes.flatMap(route => transformElegantRouteToVueRoute(route, layouts, views));
}

/**
 * transform elegant route to vue route
 * @param route elegant const route
 * @param layouts layout components
 * @param views view components
 */
function transformElegantRouteToVueRoute(
  route: ElegantConstRoute,
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  const LAYOUT_PREFIX = 'layout.';
  const VIEW_PREFIX = 'view.';
  const ROUTE_DEGREE_SPLITTER = '_';
  const FIRST_LEVEL_ROUTE_COMPONENT_SPLIT = '$';

  function isLayout(component: string) {
    return component.startsWith(LAYOUT_PREFIX);
  }

  function getLayoutName(component: string) {
    const layout = component.replace(LAYOUT_PREFIX, '');

    if(!layouts[layout]) {
      throw new Error(`Layout component "${layout}" not found`);
    }

    return layout;
  }

  function isView(component: string) {
    return component.startsWith(VIEW_PREFIX);
  }

  function getViewName(component: string) {
    const view = component.replace(VIEW_PREFIX, '');

    if(!views[view]) {
      throw new Error(`View component "${view}" not found`);
    }

    return view;
  }

  function isFirstLevelRoute(item: ElegantConstRoute) {
    return !item.name.includes(ROUTE_DEGREE_SPLITTER);
  }

  function isSingleLevelRoute(item: ElegantConstRoute) {
    return isFirstLevelRoute(item) && !item.children?.length;
  }

  function getSingleLevelRouteComponent(component: string) {
    const [layout, view] = component.split(FIRST_LEVEL_ROUTE_COMPONENT_SPLIT);

    return {
      layout: getLayoutName(layout),
      view: getViewName(view)
    };
  }

  const vueRoutes: RouteRecordRaw[] = [];

  // add props: true to route
  if (route.path.includes(':') && !route.props) {
    route.props = true;
  }

  const { name, path, component, children, ...rest } = route;

  const vueRoute = { name, path, ...rest } as RouteRecordRaw;

  try {
    if (component) {
      if (isSingleLevelRoute(route)) {
        const { layout, view } = getSingleLevelRouteComponent(component);

        const singleLevelRoute: RouteRecordRaw = {
          path,
          component: layouts[layout],
          meta: {
            title: route.meta?.title || ''
          },
          children: [
            {
              name,
              path: '',
              component: views[view],
              ...rest
            } as RouteRecordRaw
          ]
        };

        return [singleLevelRoute];
      }

      if (isLayout(component)) {
        const layoutName = getLayoutName(component);

        vueRoute.component = layouts[layoutName];
      }

      if (isView(component)) {
        const viewName = getViewName(component);

        vueRoute.component = views[viewName];
      }

    }
  } catch (error: any) {
    console.error(`Error transforming route "${route.name}": ${error.toString()}`);
    return [];
  }

  // add redirect to child
  if (children?.length && !vueRoute.redirect) {
    vueRoute.redirect = {
      name: children[0].name
    };
  }

  if (children?.length) {
    const childRoutes = children.flatMap(child => transformElegantRouteToVueRoute(child, layouts, views));

    if(isFirstLevelRoute(route)) {
      vueRoute.children = childRoutes;
    } else {
      vueRoutes.push(...childRoutes);
    }
  }

  vueRoutes.unshift(vueRoute);

  return vueRoutes;
}

/**
 * map of route name and route path
 */
const routeMap: RouteMap = {
  "root": "/",
  "not-found": "/:pathMatch(.*)*",
  "exception": "/exception",
  "exception_403": "/exception/403",
  "exception_404": "/exception/404",
  "exception_500": "/exception/500",
  "document": "/document",
  "document_project": "/document/project",
  "document_project-link": "/document/project-link",
  "document_vue": "/document/vue",
  "document_vite": "/document/vite",
  "document_unocss": "/document/unocss",
  "document_naive": "/document/naive",
  "document_antd": "/document/antd",
  "403": "/403",
  "404": "/404",
  "500": "/500",
  "about": "/about",
  "demo": "/demo",
  "demo_function": "/demo/function",
  "demo_function_hide-child": "/demo/function/hide-child",
  "demo_function_hide-child_one": "/demo/function/hide-child/one",
  "demo_function_hide-child_three": "/demo/function/hide-child/three",
  "demo_function_hide-child_two": "/demo/function/hide-child/two",
  "demo_function_multi-tab": "/demo/function/multi-tab",
  "demo_function_request": "/demo/function/request",
  "demo_function_super-page": "/demo/function/super-page",
  "demo_function_tab": "/demo/function/tab",
  "demo_function_toggle-auth": "/demo/function/toggle-auth",
  "demo_multi-menu": "/demo/multi-menu",
  "demo_multi-menu_first": "/demo/multi-menu/first",
  "demo_multi-menu_first_child": "/demo/multi-menu/first/child",
  "demo_multi-menu_second": "/demo/multi-menu/second",
  "demo_multi-menu_second_child": "/demo/multi-menu/second/child",
  "demo_multi-menu_second_child_home": "/demo/multi-menu/second/child/home",
  "demo_plugin": "/demo/plugin",
  "demo_plugin_barcode": "/demo/plugin/barcode",
  "demo_plugin_charts": "/demo/plugin/charts",
  "demo_plugin_charts_echarts": "/demo/plugin/charts/echarts",
  "demo_plugin_copy": "/demo/plugin/copy",
  "demo_plugin_editor": "/demo/plugin/editor",
  "demo_plugin_editor_markdown": "/demo/plugin/editor/markdown",
  "demo_plugin_editor_quill": "/demo/plugin/editor/quill",
  "demo_plugin_excel": "/demo/plugin/excel",
  "demo_plugin_gantt": "/demo/plugin/gantt",
  "demo_plugin_icon": "/demo/plugin/icon",
  "demo_plugin_map": "/demo/plugin/map",
  "demo_plugin_pdf": "/demo/plugin/pdf",
  "demo_plugin_pinyin": "/demo/plugin/pinyin",
  "demo_plugin_print": "/demo/plugin/print",
  "demo_plugin_swiper": "/demo/plugin/swiper",
  "demo_plugin_typeit": "/demo/plugin/typeit",
  "demo_plugin_video": "/demo/plugin/video",
  "home": "/home",
  "iframe-page": "/iframe-page/:url",
  "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?",
  "manage": "/manage",
  "manage_api": "/manage/api",
  "manage_menu": "/manage/menu",
  "manage_platform": "/manage/platform",
  "manage_role": "/manage/role",
  "manage_tenant": "/manage/tenant",
  "manage_user": "/manage/user",
  "manage_user-center": "/manage/user-center",
  "manage_user-detail": "/manage/user-detail/:id"
};

/**
 * get route path by route name
 * @param name route name
 */
export function getRoutePath<T extends RouteKey>(name: T) {
  return routeMap[name];
}

/**
 * get route name by route path
 * @param path route path
 */
export function getRouteName(path: RoutePath) {
  const routeEntries = Object.entries(routeMap) as [RouteKey, RoutePath][];

  const routeName: RouteKey | null = routeEntries.find(([, routePath]) => routePath === path)?.[0] || null;

  return routeName;
}
