/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "exception": "/exception";
    "exception_403": "/exception/403";
    "exception_404": "/exception/404";
    "exception_500": "/exception/500";
    "document": "/document";
    "document_project": "/document/project";
    "document_project-link": "/document/project-link";
    "document_vue": "/document/vue";
    "document_vite": "/document/vite";
    "document_unocss": "/document/unocss";
    "document_naive": "/document/naive";
    "document_antd": "/document/antd";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "about": "/about";
    "demo": "/demo";
    "demo_function": "/demo/function";
    "demo_function_hide-child": "/demo/function/hide-child";
    "demo_function_hide-child_one": "/demo/function/hide-child/one";
    "demo_function_hide-child_three": "/demo/function/hide-child/three";
    "demo_function_hide-child_two": "/demo/function/hide-child/two";
    "demo_function_multi-tab": "/demo/function/multi-tab";
    "demo_function_request": "/demo/function/request";
    "demo_function_super-page": "/demo/function/super-page";
    "demo_function_tab": "/demo/function/tab";
    "demo_function_toggle-auth": "/demo/function/toggle-auth";
    "demo_multi-menu": "/demo/multi-menu";
    "demo_multi-menu_first": "/demo/multi-menu/first";
    "demo_multi-menu_first_child": "/demo/multi-menu/first/child";
    "demo_multi-menu_second": "/demo/multi-menu/second";
    "demo_multi-menu_second_child": "/demo/multi-menu/second/child";
    "demo_multi-menu_second_child_home": "/demo/multi-menu/second/child/home";
    "demo_plugin": "/demo/plugin";
    "demo_plugin_barcode": "/demo/plugin/barcode";
    "demo_plugin_charts": "/demo/plugin/charts";
    "demo_plugin_charts_echarts": "/demo/plugin/charts/echarts";
    "demo_plugin_copy": "/demo/plugin/copy";
    "demo_plugin_editor": "/demo/plugin/editor";
    "demo_plugin_editor_markdown": "/demo/plugin/editor/markdown";
    "demo_plugin_editor_quill": "/demo/plugin/editor/quill";
    "demo_plugin_excel": "/demo/plugin/excel";
    "demo_plugin_gantt": "/demo/plugin/gantt";
    "demo_plugin_icon": "/demo/plugin/icon";
    "demo_plugin_map": "/demo/plugin/map";
    "demo_plugin_pdf": "/demo/plugin/pdf";
    "demo_plugin_pinyin": "/demo/plugin/pinyin";
    "demo_plugin_print": "/demo/plugin/print";
    "demo_plugin_swiper": "/demo/plugin/swiper";
    "demo_plugin_typeit": "/demo/plugin/typeit";
    "demo_plugin_video": "/demo/plugin/video";
    "home": "/home";
    "iframe-page": "/iframe-page/:url";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "manage": "/manage";
    "manage_api": "/manage/api";
    "manage_menu": "/manage/menu";
    "manage_platform": "/manage/platform";
    "manage_role": "/manage/role";
    "manage_tenant": "/manage/tenant";
    "manage_user": "/manage/user";
    "manage_user-center": "/manage/user-center";
    "manage_user-detail": "/manage/user-detail/:id";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
    | "exception"
    | "exception_403"
    | "exception_404"
    | "exception_500"
    | "document"
    | "document_project"
    | "document_project-link"
    | "document_vue"
    | "document_vite"
    | "document_unocss"
    | "document_naive"
    | "document_antd"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "about"
    | "demo"
    | "home"
    | "iframe-page"
    | "login"
    | "manage"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception"
    | "document"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "login"
    | "about"
    | "demo_function_hide-child_one"
    | "demo_function_hide-child_three"
    | "demo_function_hide-child_two"
    | "demo_function_multi-tab"
    | "demo_function_request"
    | "demo_function_super-page"
    | "demo_function_tab"
    | "demo_function_toggle-auth"
    | "demo_multi-menu_first_child"
    | "demo_multi-menu_second_child_home"
    | "demo_plugin_barcode"
    | "demo_plugin_charts_echarts"
    | "demo_plugin_copy"
    | "demo_plugin_editor_markdown"
    | "demo_plugin_editor_quill"
    | "demo_plugin_excel"
    | "demo_plugin_gantt"
    | "demo_plugin_icon"
    | "demo_plugin_map"
    | "demo_plugin_pdf"
    | "demo_plugin_pinyin"
    | "demo_plugin_print"
    | "demo_plugin_swiper"
    | "demo_plugin_typeit"
    | "demo_plugin_video"
    | "home"
    | "manage_api"
    | "manage_menu"
    | "manage_platform"
    | "manage_role"
    | "manage_tenant"
    | "manage_user-center"
    | "manage_user-detail"
    | "manage_user"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception_403"
    | "exception_404"
    | "exception_500"
    | "document_project"
    | "document_project-link"
    | "document_vue"
    | "document_vite"
    | "document_unocss"
    | "document_naive"
    | "document_antd"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;
  
  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;
  
  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
